"use client";

import { useEffect, useState } from "react";
import { FiCheckCircle, FiDownload, FiExternalLink } from "react-icons/fi";
import { toast } from "sonner";
import { Footer, Nav } from "../ui";
import { WalletButton } from "../payment-ui";
import { readWalletSession, restoreWallet, type WalletSession } from "@/lib/payments/wallet";
import type { InvoiceRecord } from "@/lib/invoices/types";
import { explorer } from "@/lib/payments/model";

export default function InvoicePublic({ publicId }: { publicId: string }) {
  const [invoice,setInvoice]=useState<InvoiceRecord|null>(null); const [wallet,setWallet]=useState<WalletSession|null>(null); const [asset,setAsset]=useState<"SOL"|"USDC">("SOL"); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{const saved=readWalletSession();if(saved)setWallet(restoreWallet(saved.name,saved.address,saved.chain));},[]);
  useEffect(()=>{let active=true;const load=()=>fetch("/api/public/invoices/"+publicId).then(async(r)=>{const data=await r.json() as InvoiceRecord & { error?: string };if(!r.ok)throw new Error(data.error||"Invoice not found.");if(active){setInvoice(data);if(data.acceptedAssets?.[0])setAsset(data.acceptedAssets[0]);}}).catch((e)=>{if(active)setError(e instanceof Error?e.message:"Invoice unavailable.");});load();const timer=window.setInterval(()=>{if(invoice?.status!=="PAID")load();},5000);return()=>{active=false;window.clearInterval(timer);};},[publicId,invoice?.status]);
  async function pay(){if(!wallet){toast.error("Connect a wallet before paying.");return;}setBusy(true);try{const r=await fetch("/api/public/invoices/"+publicId+"/payment-intents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset})});const data=await r.json() as { paymentId?: string; error?: string };if(!r.ok)throw new Error(data.error||"Could not start checkout.");window.location.assign("/pay/"+data.paymentId);}catch(e){toast.error(e instanceof Error?e.message:"Could not start checkout.");}finally{setBusy(false);}}
  const card=<main className="page-shell"><section className="panel invoice-public">{error?<><h1>Invoice unavailable</h1><p>{error}</p></>:!invoice?<p>Loading invoice...</p>:<><div className="invoice-public-head"><div><span className="eyebrow">AUNO INVOICE</span><h1>{invoice.title}</h1><p>{invoice.description}</p></div><span className={"invoice-status "+invoice.status.toLowerCase()}>{invoice.status}</span></div><div className="invoice-public-grid"><div><span>Invoice</span><strong>{invoice.invoiceNumber}</strong></div><div><span>Due</span><strong>{invoice.dueDate}</strong></div><div><span>Customer</span><strong>{invoice.customerName||"Customer"}</strong></div><div><span>Payment</span><strong>{invoice.accountingCurrency} only</strong></div></div><div className="invoice-public-items">{invoice.items.map((item,index)=><div key={index}><span>{item.description}<small>{item.quantity} x {item.unitPrice}</small></span><strong>{item.lineTotal} {invoice.accountingCurrency}</strong></div>)}</div><div className="invoice-public-total"><span>Total</span><strong>{invoice.totalAmount} {invoice.accountingCurrency}</strong></div>{invoice.status==="PAID"?<div className="invoice-paid"><FiCheckCircle/><div><strong>Payment verified</strong><p>This invoice was settled and verified at finalized commitment.</p>{invoice.paidPaymentId&&<a className="text-link" href={"/receipt/"+invoice.paidPaymentId}>View receipt <FiExternalLink/></a>}</div></div>:invoice.status==="VOIDED"?<p className="notice error">This invoice is voided and cannot be paid.</p>:<><div className="invoice-pay-controls"><WalletButton session={wallet} onChange={setWallet}/><select value={asset} onChange={(e)=>setAsset(e.target.value as "SOL"|"USDC")}><option value="SOL">Pay with SOL</option><option value="USDC">Pay with USDC</option></select></div><button className="button wide" disabled={busy||!wallet} onClick={()=>void pay()}>{busy?"Opening checkout...":"Continue to secure checkout"}</button></>}<div className="invoice-public-links"><a className="text-link" href={"/api/public/invoices/"+publicId+"/pdf"}><FiDownload/> Download PDF</a></div></>}</section></main>;
  return <><Nav/><>{card}</><Footer/></>;
}
