import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const payments = sqliteTable('payments',{id:text('id').primaryKey(),network:text('network').notNull().default('devnet'),merchantWallet:text('merchant_wallet').notNull(),title:text('title').notNull(),description:text('description').notNull(),asset:text('asset').notNull(),amount:text('amount').notNull(),amountBaseUnits:text('amount_base_units').notNull(),recipients:text('recipients').notNull(),reference:text('reference').notNull(),expiresAt:integer('expires_at').notNull(),status:text('status').notNull(),transactionSignature:text('transaction_signature'),payer:text('payer'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),paidAt:integer('paid_at'),creationKey:text('creation_key').notNull(),activeAttempt:text('active_attempt'),leaseUntil:integer('lease_until'),invoiceId:text('invoice_id'),repeatSplitId:text('repeat_split_id'),repeatSplitName:text('repeat_split_name')},t=>[index('merchant_network_created_idx').on(t.merchantWallet,t.network,t.createdAt),uniqueIndex('creation_key_idx').on(t.creationKey),uniqueIndex('signature_unique_idx').on(t.transactionSignature)]);
export const attempts=sqliteTable('attempts',{id:text('id').primaryKey(),paymentId:text('payment_id').notNull(),payer:text('payer').notNull(),message:text('message').notNull(),transaction:text('transaction').notNull(),lastValidBlockHeight:integer('last_valid_block_height').notNull(),createdAt:integer('created_at').notNull(),signature:text('signature'),status:text('status').notNull()},t=>[index('attempt_payment_idx').on(t.paymentId)]);
export const paymentAttempts=sqliteTable('payment_attempts',{id:text('id').primaryKey(),paymentId:text('payment_id').notNull(),payer:text('payer').notNull(),messageHash:text('message_hash').notNull(),attemptTokenHash:text('attempt_token_hash').notNull(),lastValidBlockHeight:integer('last_valid_block_height').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),signature:text('signature'),status:text('status').notNull()},t=>[index('payment_attempt_payment_created_idx').on(t.paymentId,t.createdAt),index('payment_attempt_status_updated_idx').on(t.status,t.updatedAt),uniqueIndex('payment_attempt_signature_idx').on(t.signature)]);
export const paymentRateLimits=sqliteTable('payment_rate_limits',{bucket:text('bucket').primaryKey(),windowStartedAt:integer('window_started_at').notNull(),count:integer('count').notNull()});

export const invoices=sqliteTable('invoices',{id:text('id').primaryKey(),publicId:text('public_id').notNull(),merchantWallet:text('merchant_wallet').notNull(),invoiceNumber:text('invoice_number').notNull(),title:text('title').notNull(),description:text('description').notNull(),customerName:text('customer_name').notNull(),customerEmail:text('customer_email').notNull(),accountingCurrency:text('accounting_currency').notNull(),subtotal:text('subtotal').notNull(),discountType:text('discount_type').notNull(),discountValue:text('discount_value').notNull(),discountAmount:text('discount_amount').notNull(),taxLabel:text('tax_label').notNull(),taxRate:text('tax_rate').notNull(),taxAmount:text('tax_amount').notNull(),additionalFees:text('additional_fees').notNull(),totalAmount:text('total_amount').notNull(),items:text('items').notNull(),recipientWallet:text('recipient_wallet').notNull(),acceptedAssets:text('accepted_assets').notNull(),status:text('status').notNull(),issueDate:text('issue_date').notNull(),dueDate:text('due_date').notNull(),terms:text('terms').notNull(),notes:text('notes').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),publishedAt:integer('published_at'),paidAt:integer('paid_at'),voidedAt:integer('voided_at'),paidPaymentId:text('paid_payment_id'),creationKey:text('creation_key').notNull()},t=>[uniqueIndex('invoice_public_id_idx').on(t.publicId),index('invoice_merchant_created_idx').on(t.merchantWallet,t.createdAt),index('invoice_status_updated_idx').on(t.status,t.updatedAt),uniqueIndex('invoice_creation_key_idx').on(t.creationKey)]);

export const repeatSplits=sqliteTable('repeat_splits',{id:text('id').primaryKey(),network:text('network').notNull(),ownerWallet:text('owner_wallet').notNull(),name:text('name').notNull(),description:text('description').notNull(),asset:text('asset').notNull(),amount:text('amount').notNull(),allocationType:text('allocation_type').notNull().default('percentage'),recipients:text('recipients').notNull(),revision:integer('revision').notNull().default(1),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),lastUsedAt:integer('last_used_at'),executionCount:integer('execution_count').notNull().default(0),deletedAt:integer('deleted_at')},t=>[index('repeat_splits_owner_network').on(t.ownerWallet,t.network,t.createdAt)]);
export const repeatSplitAuthorizations=sqliteTable('repeat_split_authorizations',{nonce:text('nonce').primaryKey(),expiresAt:integer('expires_at').notNull()});
import { sql } from 'drizzle-orm';
export const savedRecipients=sqliteTable('saved_recipients',{id:text('id').primaryKey(),ownerWallet:text('owner_wallet').notNull(),name:text('name').notNull(),address:text('address').notNull(),note:text('note').notNull().default(''),revision:integer('revision').notNull().default(1),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),deletedAt:integer('deleted_at')},t=>[index('saved_recipients_owner_created').on(t.ownerWallet,t.createdAt),uniqueIndex('saved_recipients_owner_address').on(t.ownerWallet,t.address).where(sql`${t.deletedAt} IS NULL`)]);
export const savedRecipientAuthorizations=sqliteTable('saved_recipient_authorizations',{nonce:text('nonce').primaryKey(),expiresAt:integer('expires_at').notNull()});
