import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const root = new URL('..', import.meta.url);
const checkout = await readFile(new URL('app/checkout.tsx', root), 'utf8');
const paymentUi = await readFile(new URL('app/payment-ui.tsx', root), 'utf8');
const wallet = await readFile(new URL('lib/payments/wallet.ts', root), 'utf8');
const page = await readFile(new URL('app/pay/[id]/page.tsx', root), 'utf8');
const splitPage = await readFile(new URL('app/split/page.tsx', root), 'utf8');
const capabilities = await readFile(new URL('app/api/capabilities/route.ts', root), 'utf8');

assert.doesNotMatch(page, /payments\/server/);
assert.doesNotMatch(page, /initialPayment=/);
assert.match(page, /<Checkout id=/);
assert.match(checkout, /initialPayment/);
assert.match(checkout, /embedded = false/);
assert.match(checkout, /onBack/);
assert.match(checkout, /readCheckoutProgress/);
assert.match(checkout, /writeCheckoutProgress/);
assert.match(checkout, /readWalletSession/);
assert.match(checkout, /saveWalletSession/);
assert.match(checkout, /restoreWallet\(saved\.name, saved\.address, saved\.chain\)/);
assert.match(checkout, /wallet\.assertActive\(\)/);
assert.match(paymentUi, /saveWalletSession/);
assert.match(paymentUi, /useMainnetSplitsCapability/);
assert.match(splitPage, /mainnetSplitsEnabled/);
assert.match(capabilities, /publicCapabilities/);
assert.match(paymentUi, /clearWalletSession/);
assert.match(wallet, /@wallet-standard\/app/);
assert.match(wallet, /standard:connect/);
assert.match(wallet, /solana:signMessage/);
assert.match(wallet, /solana:signTransaction/);
assert.match(wallet, /function activeContext/);
assert.doesNotMatch(wallet, /phantom/i);
assert.match(checkout, /sessionStorage/);
assert.doesNotMatch(checkout, /localStorage/);
assert.match(checkout, /await import\(\"@\/lib\/payments\/wallet\"\)/);
assert.doesNotMatch(checkout, /import \{ availableWallets, connectWallet/);
assert.match(checkout, /recipient\.address === wallet\.address/);
assert.match(checkout, /<Nav network=\{payment\?\.network === "mainnet-beta" \? "mainnet" : undefined\}/);
assert.match(checkout, /<Footer network=\{payment\?\.network === "mainnet-beta" \? "mainnet" : undefined\}/);
assert.doesNotMatch(checkout, /new Date\(payment\.expiresAt\)\.toLocaleString/);
assert.match(checkout, /new Date\(payment\.expiresAt\)\.toISOString/);

console.log('PASS checkout loads payment through the API and blocks payer-recipient self-payments');
