import assert from 'node:assert/strict';
import { readFileSync,writeFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import ts from 'typescript';
async function build(options){let source=readFileSync(options.entryPoints[0],'utf8');source=source.replace("import { env } from 'cloudflare:workers';",'const env = globalThis.__AUNO_ENV__;').replace("from './model'","from './model.mjs'");writeFileSync(options.outfile,ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);}
import { Keypair,Connection,Transaction,PublicKey,SystemProgram } from '@solana/web3.js';
import bs58 from 'bs58';
import nacl from 'tweetnacl';
await build({entryPoints:['lib/payments/model.ts'],outfile:'work/model.mjs',bundle:true,platform:'node',format:'esm'});
const model=await import('../work/model.mjs');
let passed=0;
function check(name,fn){fn();console.log('PASS',name);passed++}
check('SOL and USDC precision',()=>{assert.equal(model.toBaseUnits('0.000000001',9),1n);assert.equal(model.toBaseUnits('100.000001',6),100000001n);assert.equal(model.displayUnits(100000000n,6),'100')});
check('Reject unsafe decimal input',()=>{for(const x of ['1e3','-1','0','NaN','1.0000001','9007199254740992'])assert.throws(()=>model.toBaseUnits(x,6));});
check('Split rounding conserves base units',()=>{assert.deepEqual(model.allocate(101n,[8000,1500,500]),[81n,15n,5n]);assert.throws(()=>model.allocate(1n,[5000,5000]));assert.throws(()=>model.allocate(100n,[5000,4900]));});
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('drizzle/0000_lush_the_executioner.sql','utf8'));
function statement(sql,args=[]){return {bind(...v){return statement(sql,v)},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const result=sqlite.prepare(sql).run(...args);return {meta:{changes:result.changes}}}}};
globalThis.__AUNO_ENV__={DB:{prepare:statement,async batch(stmts){sqlite.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}}};
await build({entryPoints:['lib/payments/server.ts'],outfile:'work/server-test.mjs',bundle:true,packages:'external',platform:'node',format:'esm',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'test-env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__AUNO_ENV__;',loader:'js'}))}}]});
const server=await import('../work/server-test.mjs');
const merchant=Keypair.generate(),payer=Keypair.generate();
const origin='http://localhost:5173';
const payload=JSON.stringify({merchantWallet:merchant.publicKey.toBase58(),title:'Controlled integration test',description:'Test record',asset:'SOL',amount:'0.001',recipient:merchant.publicKey.toBase58(),reference:'TEST',expiresAt:Date.now()+3600000,timestamp:Date.now(),origin});
const sig=bs58.encode(nacl.sign.detached(new TextEncoder().encode(model.creationMessage(payload)),merchant.secretKey));
const request=body=>new Request(origin+'/api/payments',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const p=await server.createPayment(request({payload,signature:sig}));assert.equal(p.status,'ACTIVE');assert.equal((await server.createPayment(request({payload,signature:sig}))).id,p.id);passed++;console.log('PASS signed creation, persistence, duplicate creation');
await assert.rejects(()=>server.createPayment(request({payload:payload.replace('0.001','0.002'),signature:sig})));passed++;console.log('PASS forged merchant data rejected');
check('Address validation',()=>{assert.equal(server.address(merchant.publicKey.toBase58()),merchant.publicKey.toBase58());assert.throws(()=>server.address('fake-wallet'))});
Connection.prototype.getGenesisHash=async()=> 'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG';Connection.prototype.getLatestBlockhash=async()=>({blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:10000});Connection.prototype.getBlockHeight=async()=>100;Connection.prototype.sendRawTransaction=async bytes=>bs58.encode(Transaction.from(bytes).signature);
const prepared=await server.preparePayment(request({payer:payer.publicKey.toBase58()}),p.id);const transaction=Transaction.from(Buffer.from(prepared.transaction,'base64'));transaction.sign(payer);
const submitted=await server.submitPayment(request({attemptId:prepared.attemptId,transaction:transaction.serialize().toString('base64')}),p.id);assert.equal(submitted.status,'SUBMITTED');passed++;console.log('PASS exact signed submission');
const memo=`auno:${p.id}:${prepared.attemptId}`;
let wrong=false,failed=false;
Connection.prototype.getParsedTransaction=async()=>({blockTime:Math.floor(Date.now()/1000),meta:{err:failed?{InstructionError:[0,'failed']}:null},transaction:{message:{accountKeys:[{pubkey:payer.publicKey,signer:true},{pubkey:merchant.publicKey,signer:false}],instructions:[{programId:SystemProgram.programId,parsed:{type:'transfer',info:{source:payer.publicKey.toBase58(),destination:wrong?Keypair.generate().publicKey.toBase58():merchant.publicKey.toBase58(),lamports:1000000}}},{programId:new PublicKey(model.MEMO_PROGRAM),parsed:memo}]}}});Connection.prototype.getTransaction=async()=>({transaction:{message:transaction.compileMessage()}});
wrong=true;await assert.rejects(()=>server.verifyPayment(p.id,submitted.signature));assert.notEqual((await server.getPayment(p.id)).status,'PAID');wrong=false;failed=true;await assert.rejects(()=>server.verifyPayment(p.id,submitted.signature));failed=false;passed++;console.log('PASS wrong recipient and failed transaction cannot become PAID');
const paid=await server.verifyPayment(p.id,submitted.signature);assert.equal(paid.status,'PAID');assert.equal((await server.verifyPayment(p.id,submitted.signature)).transactionSignature,submitted.signature);await assert.rejects(()=>server.verifyPayment(p.id,bs58.encode(new Uint8Array(64).fill(2))));passed++;console.log('PASS verified receipt, duplicate verification and wrong signature protection');
const expired=await server.getPayment(p.id);assert.equal(expired.status,'PAID');sqlite.prepare("UPDATE payments SET status='ACTIVE',expires_at=? WHERE id=?").run(Date.now()-1000,p.id);assert.equal((await server.getPayment(p.id)).status,'EXPIRED');await assert.rejects(()=>server.preparePayment(request({payer:payer.publicKey.toBase58()}),p.id));passed++;console.log('PASS expiration blocks payment preparation');
console.log(`${passed} test groups passed. RPC fixtures are controlled; these are not real devnet transactions.`);


// Additional USDC verification fixtures; no network settlement is represented.
const { getAssociatedTokenAddress,TOKEN_PROGRAM_ID }=await import('@solana/spl-token');
const usdcPayload=JSON.stringify({...JSON.parse(payload),asset:'USDC',amount:'1.25',timestamp:Date.now()});const usdcSig=bs58.encode(nacl.sign.detached(new TextEncoder().encode(model.creationMessage(usdcPayload)),merchant.secretKey));const usdc=await server.createPayment(request({payload:usdcPayload,signature:usdcSig}));const usdcPrepared=await server.preparePayment(request({payer:payer.publicKey.toBase58()}),usdc.id);const usdcTx=Transaction.from(Buffer.from(usdcPrepared.transaction,'base64'));usdcTx.sign(payer);const usdcSubmitted=await server.submitPayment(request({attemptId:usdcPrepared.attemptId,transaction:usdcTx.serialize().toString('base64')}),usdc.id);const mint=new PublicKey(model.ASSETS.USDC.mint);const source=await getAssociatedTokenAddress(mint,payer.publicKey);const dest=await getAssociatedTokenAddress(mint,merchant.publicKey);let badMint=true;
Connection.prototype.getParsedTransaction=async()=>({blockTime:Math.floor(Date.now()/1000),meta:{err:null,postTokenBalances:[{accountIndex:2,mint:mint.toBase58(),owner:merchant.publicKey.toBase58()}]},transaction:{message:{accountKeys:[{pubkey:payer.publicKey,signer:true},{pubkey:merchant.publicKey,signer:false},{pubkey:dest,signer:false}],instructions:[{programId:TOKEN_PROGRAM_ID,parsed:{type:'transferChecked',info:{source:source.toBase58(),destination:dest.toBase58(),authority:payer.publicKey.toBase58(),mint:badMint?payer.publicKey.toBase58():mint.toBase58(),tokenAmount:{amount:'1250000',decimals:6}}}},{programId:new PublicKey(model.MEMO_PROGRAM),parsed:`auno:${usdc.id}:${usdcPrepared.attemptId}`}]}}});Connection.prototype.getTransaction=async()=>({transaction:{message:usdcTx.compileMessage()}});await assert.rejects(()=>server.verifyPayment(usdc.id,usdcSubmitted.signature));assert.notEqual((await server.getPayment(usdc.id)).status,'PAID');badMint=false;assert.equal((await server.verifyPayment(usdc.id,usdcSubmitted.signature)).status,'PAID');passed++;console.log('PASS USDC rejects wrong mint and verifies correct amount, owner and message');console.log(`FINAL: ${passed} controlled test groups passed.`);
